#!/bin/bash

GIT_ROOT="$( git rev-parse --show-toplevel )"
cd "${GIT_ROOT}/demo" || exit

bundle 
bundle update

# bundle exec jekyll clean # Ensure all hooks get called

if [ "$1" == -a ]; then
  bundle exec ../binstub/jekyll new_post
elif [ "$1" == -r ]; then
  bundle exec ../binstub/jekyll new_post
else
  bundle exec rdbg -O --port=0 -- ../binstub/jekyll new_post
fi
