# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.2'
gem 'ptools'
gem 'webrick'

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll-new_post', path: '../'
  gem 'kramdown'
end

# Debugging:
gem 'debase', '0.2.5.beta2', require: false
gem 'debase-ruby_core_source', '~> 0.10.15', require: false
gem 'ruby-debug-ide', require: false
# gem 'rake', '~> 13.0', require: false
# gem 'rspec', require: false
# gem 'rubocop', '= 1.18.0', require: false
