source 'https://rubygems.org'

gem 'jekyll', '~> 4.3.2', require: false

group :jekyll_plugins do
  gem 'jekyll-assets'
  gem 'jekyll-environment-variables'
  gem 'jekyll-new_post', path: '../'
  gem 'kramdown'
end

group :test, :development do
  gem 'debug', '>= 1.0.0', require: false
  gem 'ptools'
  gem 'rake', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'rubocop-md', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec', require: false
end
